name: GraalVM Workflow

on:
  push:
    
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Graalvm
      uses: graalvm/setup-graalvm@v1.2.6
      with:
        java-version:  '21.0.5'

    # Step 3: Verify GraalVM installation
    - name: Compile and deploy WSArch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn package
        mvn test
        export GITHUB_ACTOR=luislara
        export GITHUB_TOKEN=$GITHUB_TOKEN
        echo ACTOR $GITHUB_ACTOR
        echo $GITHUB_TOKEN
        mvn deploy
  
